# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lzd/Desktop/electron-crypto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lzd/Desktop/electron-crypto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lzd/Desktop/electron-crypto/CMakeFiles /home/lzd/Desktop/electron-crypto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lzd/Desktop/electron-crypto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sm2

# Build rule for target.
sm2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sm2
.PHONY : sm2

# fast build rule for target.
sm2/fast:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/build
.PHONY : sm2/fast

SM2/ec_param.o: SM2/ec_param.cpp.o

.PHONY : SM2/ec_param.o

# target to build an object file
SM2/ec_param.cpp.o:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/ec_param.cpp.o
.PHONY : SM2/ec_param.cpp.o

SM2/ec_param.i: SM2/ec_param.cpp.i

.PHONY : SM2/ec_param.i

# target to preprocess a source file
SM2/ec_param.cpp.i:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/ec_param.cpp.i
.PHONY : SM2/ec_param.cpp.i

SM2/ec_param.s: SM2/ec_param.cpp.s

.PHONY : SM2/ec_param.s

# target to generate assembly for a file
SM2/ec_param.cpp.s:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/ec_param.cpp.s
.PHONY : SM2/ec_param.cpp.s

SM2/part5.o: SM2/part5.cpp.o

.PHONY : SM2/part5.o

# target to build an object file
SM2/part5.cpp.o:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/part5.cpp.o
.PHONY : SM2/part5.cpp.o

SM2/part5.i: SM2/part5.cpp.i

.PHONY : SM2/part5.i

# target to preprocess a source file
SM2/part5.cpp.i:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/part5.cpp.i
.PHONY : SM2/part5.cpp.i

SM2/part5.s: SM2/part5.cpp.s

.PHONY : SM2/part5.s

# target to generate assembly for a file
SM2/part5.cpp.s:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/part5.cpp.s
.PHONY : SM2/part5.cpp.s

SM2/pcB.o: SM2/pcB.cpp.o

.PHONY : SM2/pcB.o

# target to build an object file
SM2/pcB.cpp.o:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/pcB.cpp.o
.PHONY : SM2/pcB.cpp.o

SM2/pcB.i: SM2/pcB.cpp.i

.PHONY : SM2/pcB.i

# target to preprocess a source file
SM2/pcB.cpp.i:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/pcB.cpp.i
.PHONY : SM2/pcB.cpp.i

SM2/pcB.s: SM2/pcB.cpp.s

.PHONY : SM2/pcB.s

# target to generate assembly for a file
SM2/pcB.cpp.s:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/pcB.cpp.s
.PHONY : SM2/pcB.cpp.s

SM2/sm2.o: SM2/sm2.cpp.o

.PHONY : SM2/sm2.o

# target to build an object file
SM2/sm2.cpp.o:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm2.cpp.o
.PHONY : SM2/sm2.cpp.o

SM2/sm2.i: SM2/sm2.cpp.i

.PHONY : SM2/sm2.i

# target to preprocess a source file
SM2/sm2.cpp.i:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm2.cpp.i
.PHONY : SM2/sm2.cpp.i

SM2/sm2.s: SM2/sm2.cpp.s

.PHONY : SM2/sm2.s

# target to generate assembly for a file
SM2/sm2.cpp.s:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm2.cpp.s
.PHONY : SM2/sm2.cpp.s

SM2/sm2_ec_key.o: SM2/sm2_ec_key.cpp.o

.PHONY : SM2/sm2_ec_key.o

# target to build an object file
SM2/sm2_ec_key.cpp.o:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm2_ec_key.cpp.o
.PHONY : SM2/sm2_ec_key.cpp.o

SM2/sm2_ec_key.i: SM2/sm2_ec_key.cpp.i

.PHONY : SM2/sm2_ec_key.i

# target to preprocess a source file
SM2/sm2_ec_key.cpp.i:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm2_ec_key.cpp.i
.PHONY : SM2/sm2_ec_key.cpp.i

SM2/sm2_ec_key.s: SM2/sm2_ec_key.cpp.s

.PHONY : SM2/sm2_ec_key.s

# target to generate assembly for a file
SM2/sm2_ec_key.cpp.s:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm2_ec_key.cpp.s
.PHONY : SM2/sm2_ec_key.cpp.s

SM2/sm2_test_param.o: SM2/sm2_test_param.cpp.o

.PHONY : SM2/sm2_test_param.o

# target to build an object file
SM2/sm2_test_param.cpp.o:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm2_test_param.cpp.o
.PHONY : SM2/sm2_test_param.cpp.o

SM2/sm2_test_param.i: SM2/sm2_test_param.cpp.i

.PHONY : SM2/sm2_test_param.i

# target to preprocess a source file
SM2/sm2_test_param.cpp.i:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm2_test_param.cpp.i
.PHONY : SM2/sm2_test_param.cpp.i

SM2/sm2_test_param.s: SM2/sm2_test_param.cpp.s

.PHONY : SM2/sm2_test_param.s

# target to generate assembly for a file
SM2/sm2_test_param.cpp.s:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm2_test_param.cpp.s
.PHONY : SM2/sm2_test_param.cpp.s

SM2/sm3.o: SM2/sm3.cpp.o

.PHONY : SM2/sm3.o

# target to build an object file
SM2/sm3.cpp.o:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm3.cpp.o
.PHONY : SM2/sm3.cpp.o

SM2/sm3.i: SM2/sm3.cpp.i

.PHONY : SM2/sm3.i

# target to preprocess a source file
SM2/sm3.cpp.i:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm3.cpp.i
.PHONY : SM2/sm3.cpp.i

SM2/sm3.s: SM2/sm3.cpp.s

.PHONY : SM2/sm3.s

# target to generate assembly for a file
SM2/sm3.cpp.s:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/sm3.cpp.s
.PHONY : SM2/sm3.cpp.s

SM2/util.o: SM2/util.cpp.o

.PHONY : SM2/util.o

# target to build an object file
SM2/util.cpp.o:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/util.cpp.o
.PHONY : SM2/util.cpp.o

SM2/util.i: SM2/util.cpp.i

.PHONY : SM2/util.i

# target to preprocess a source file
SM2/util.cpp.i:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/util.cpp.i
.PHONY : SM2/util.cpp.i

SM2/util.s: SM2/util.cpp.s

.PHONY : SM2/util.s

# target to generate assembly for a file
SM2/util.cpp.s:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/util.cpp.s
.PHONY : SM2/util.cpp.s

SM2/xy_ecpoint.o: SM2/xy_ecpoint.cpp.o

.PHONY : SM2/xy_ecpoint.o

# target to build an object file
SM2/xy_ecpoint.cpp.o:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/xy_ecpoint.cpp.o
.PHONY : SM2/xy_ecpoint.cpp.o

SM2/xy_ecpoint.i: SM2/xy_ecpoint.cpp.i

.PHONY : SM2/xy_ecpoint.i

# target to preprocess a source file
SM2/xy_ecpoint.cpp.i:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/xy_ecpoint.cpp.i
.PHONY : SM2/xy_ecpoint.cpp.i

SM2/xy_ecpoint.s: SM2/xy_ecpoint.cpp.s

.PHONY : SM2/xy_ecpoint.s

# target to generate assembly for a file
SM2/xy_ecpoint.cpp.s:
	$(MAKE) -f CMakeFiles/sm2.dir/build.make CMakeFiles/sm2.dir/SM2/xy_ecpoint.cpp.s
.PHONY : SM2/xy_ecpoint.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sm2"
	@echo "... SM2/ec_param.o"
	@echo "... SM2/ec_param.i"
	@echo "... SM2/ec_param.s"
	@echo "... SM2/part5.o"
	@echo "... SM2/part5.i"
	@echo "... SM2/part5.s"
	@echo "... SM2/pcB.o"
	@echo "... SM2/pcB.i"
	@echo "... SM2/pcB.s"
	@echo "... SM2/sm2.o"
	@echo "... SM2/sm2.i"
	@echo "... SM2/sm2.s"
	@echo "... SM2/sm2_ec_key.o"
	@echo "... SM2/sm2_ec_key.i"
	@echo "... SM2/sm2_ec_key.s"
	@echo "... SM2/sm2_test_param.o"
	@echo "... SM2/sm2_test_param.i"
	@echo "... SM2/sm2_test_param.s"
	@echo "... SM2/sm3.o"
	@echo "... SM2/sm3.i"
	@echo "... SM2/sm3.s"
	@echo "... SM2/util.o"
	@echo "... SM2/util.i"
	@echo "... SM2/util.s"
	@echo "... SM2/xy_ecpoint.o"
	@echo "... SM2/xy_ecpoint.i"
	@echo "... SM2/xy_ecpoint.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

